#!/usr/bin/env bash
# Real javac verification for the dependency-light Amegram Module core.
# Uses portable JDK + stock android.jar + one Telegram stub.
# UI files (ModulesActivity, WelcomeSheet) need the full app sourcepath + R
# and are covered by tests/test_amegram_stages.py instead.
set -e
TC=/tmp/opencode/toolchain
if [ -f /tmp/opencode/sdk/platforms/android-36/android.jar ]; then TC_ANDROID_JAR=/tmp/opencode/sdk/platforms/android-36/android.jar; else TC_ANDROID_JAR=$TC/android.jar; fi
JDK_DIR="$(echo "$TC"/jdk-21* | cut -d' ' -f1)"
JAVAC="$JDK_DIR/bin/javac"
STUBS=/tmp/opencode/stubs
OUT=/tmp/opencode/mod-classes
SRC="$(cd "$(dirname "$0")/.." && pwd)/TMessagesProj/src/main/java"

mkdir -p "$STUBS/org/telegram/messenger" "$OUT"
cat > "$STUBS/org/telegram/messenger/ApplicationLoader.java" <<'EOF'
package org.telegram.messenger;
public class ApplicationLoader {
    public static android.content.Context applicationContext;
}
EOF

FILES="app/amegram/module/AmegramConfig.java
app/amegram/module/AmegramFeature.java
app/amegram/module/AmegramModule.java
app/amegram/module/AmegramFeatureManager.java
app/amegram/module/AmegramHooks.java
app/amegram/module/features/ghost/AmegramGhostPolicy.java
app/amegram/module/features/ghost/AmegramGhostController.java
app/amegram/module/features/player/AmegramPlayerConfig.java
app/amegram/module/features/player/AmegramPlayerFeature.java
app/amegram/module/features/badges/AmegramBadgesFeature.java
app/amegram/module/features/badges/AmegramBadgesCache.java
app/amegram/module/features/guide/AmegramGuideFeature.java
app/amegram/module/features/net/AmegramAntiBlockFeature.java
app/amegram/module/features/profile/AmegramAmeProfileFeature.java
app/amegram/module/features/system/AmegramHotfixFeature.java
app/amegram/module/features/vault/AmegramDoubleBottomFeature.java"

ABS=""
for f in $FILES; do ABS="$ABS $SRC/$f"; done

# UI stubs for the ui.* dependency of GuideFeature (generated by sibling script).
"$(dirname "$0")/verify-module-ui.sh" >/dev/null 2>&1 || true
UI_STUBS=/tmp/opencode/stubs-ui

"$JAVAC" -version
"$JAVAC" -proc:none -nowarn  -cp "$TC_ANDROID_JAR:$TC/json.jar" -sourcepath "$STUBS:$UI_STUBS" -d "$OUT" \
  "$STUBS/org/telegram/messenger/ApplicationLoader.java" $ABS \
  "$SRC/app/amegram/module/ui/AmegramModulesActivity.java" \
  "$SRC/app/amegram/module/ui/AmegramWelcomeSheet.java"
echo "MODULE-JAVAC-OK (18 module files)"
